/* WardenOne — Copyright (C) 2026 iri
   Licensed under the GNU General Public License v3 or later. See LICENSE.
   Official source: https://github.com/iri-dev/WardenOne
   Upstream filter-list attribution: CREDITS.md
   Redistributing a modified copy? GPLv3 section 5(a) requires you to mark it as changed,
   with the date, and to keep these notices intact. */
/*
 * WardenOne -- shared registrable-domain (eTLD+1) helpers.
 * ======================================================
 * Loaded by BOTH the background service worker (via importScripts) and the popup/options
 * pages (via a <script> tag) so the two can never disagree about what "this site" is for
 * Forget-Me, allowlisting, and breach lookups. This is the single source of truth -- do
 * NOT re-implement the algorithm in popup.js or background.js.
 *
 * Browser extensions do not get a platform eTLD+1 API. The ICANN half is handled by
 * the common country-code second-level rule below; the security-sensitive private half
 * is explicit. On a shared host, the tenant label is part of the site identity, so
 * alice.github.io and attacker.github.io can never share trust, cookies or allowlists.
 * Opaque cloud infrastructure is stricter still: every hostname is its own identity.
 *
 * The curated tables below are the floor. Where psl-private.js is loaded (the worker), the
 * complete private half of the Public Suffix List sits on top of them: siteIdentity() is the
 * trust-decision form and is never broader than registrableDomain(); see it for the split.
 */

const WARDENONE_PRIVATE_SUFFIXES = Object.freeze([
  'appspot.com', 'azurewebsites.net', 'blogspot.com', 'firebaseapp.com', 'fly.dev',
  'github.io', 'gitlab.io', 'glitch.me', 'herokuapp.com', 'myshopify.com',
  'netlify.app', 'notion.site', 'onrender.com', 'pages.dev', 'railway.app',
  'readthedocs.io', 'repl.co', 'replit.app', 'surge.sh', 'tumblr.com',
  'vercel.app', 'vercel.sh', 'web.app', 'wixsite.com', 'workers.dev', 'wordpress.com',
]);

/* These providers have service-specific labels between the customer and the public
 * suffix (bucket.s3.region.amazonaws.com, account.blob.core.windows.net, and so on).
 * Guessing which label owns which would merge customers again. Exact-host identity is
 * conservative, compatible with host-scoped controls, and never widens trust. */
const WARDENONE_OPAQUE_TENANT_SUFFIXES = Object.freeze([
  'amazonaws.com', 'blob.core.windows.net', 'cloudfront.net', 'googleusercontent.com',
  'storage.googleapis.com',
]);

function regDomain(host) {
  let value = String(host || '').trim().toLowerCase().replace(/\.+$/, '');
  try {
    if (/^[a-z][a-z0-9+.-]*:\/\//i.test(value)) value = new URL(value).hostname.toLowerCase();
  } catch (_) {}
  if (value[0] !== '[' && (value.match(/:/g) || []).length === 1) value = value.replace(/:\d+$/, '');
  return value.replace(/^www\./, '');
}

function wardenOneSuffixMatch(host, suffixes) {
  const h = regDomain(host);
  let found = '';
  for (const suffix of suffixes) {
    if ((h === suffix || h.endsWith('.' + suffix)) && suffix.length > found.length) found = suffix;
  }
  return found;
}

function sharedTenantSuffix(host) {
  return wardenOneSuffixMatch(host, WARDENONE_PRIVATE_SUFFIXES)
    || wardenOneSuffixMatch(host, WARDENONE_OPAQUE_TENANT_SUFFIXES);
}

function isSharedTenantHost(host) {
  const h = regDomain(host);
  const suffix = sharedTenantSuffix(h);
  return !!(suffix && h !== suffix);
}

function registrableDomain(host) {
  const h = regDomain(host);
  if (!h || h === 'localhost' || /^\d{1,3}(?:\.\d{1,3}){3}$/.test(h) || h.includes(':')) return h;
  const opaque = wardenOneSuffixMatch(h, WARDENONE_OPAQUE_TENANT_SUFFIXES);
  if (opaque) return h;
  const privateSuffix = wardenOneSuffixMatch(h, WARDENONE_PRIVATE_SUFFIXES);
  if (privateSuffix) {
    if (h === privateSuffix) return h;
    const hostParts = h.split('.');
    const suffixParts = privateSuffix.split('.');
    return hostParts.slice(-(suffixParts.length + 1)).join('.');
  }
  const parts = h.split('.').filter(Boolean);
  if (parts.length <= 2) return h;
  const last2 = parts.slice(-2).join('.');
  const multi = /^(co|com|org|net|gov|ac|edu|gob|gouv)\.[a-z]{2}$/;
  return multi.test(last2) ? parts.slice(-3).join('.') : last2;
}

function sameSiteDomain(a, b) {
  const left = registrableDomain(a);
  const right = registrableDomain(b);
  return !!(left && right && left === right);
}

/* The complete private half of the Public Suffix List, where it is loaded. The 26 entries above
 * were the platforms somebody remembered; the list has 3,300 more, and every one that was missing
 * (webflow.io was the audited case) collapsed two of its tenants into one site at the exact
 * boundary that decides whether a token may leave a page (SEC-07). The worker imports
 * psl-private.js (generated by tools/build-psl.js, reviewed when it changes). Frames and pages do
 * not carry 87 KB each: the worker tells each frame its own site with the content config, and
 * everything below degrades to the curated table when the rules are absent, so no caller is ever
 * worse off than before. Built on first use; a page that never asks never pays. */
let __wardenOnePslIndex = null;
function wardenOnePslIndex() {
  if (__wardenOnePslIndex) return __wardenOnePslIndex;
  const plain = new Set();
  const wildcard = new Set();
  const exception = new Set();
  let raw = '';
  try { if (typeof WARDENONE_PSL_PRIVATE_RULES === 'string') raw = WARDENONE_PSL_PRIVATE_RULES; } catch (_) { raw = ''; }
  for (const rule of raw.split('\n')) {
    if (!rule) continue;
    if (rule[0] === '!') exception.add(rule.slice(1));
    else if (rule.startsWith('*.')) wildcard.add(rule.slice(2));
    else plain.add(rule);
  }
  __wardenOnePslIndex = { plain, wildcard, exception, loaded: raw.length > 0 };
  return __wardenOnePslIndex;
}

/* The public suffix of a host under the private rules, by the list's own algorithm: an exception
 * rule wins outright and names the suffix minus its first label; otherwise the rule with the most
 * labels wins, a wildcard standing for exactly one label. '' when no private rule matches. */
function wardenOnePslSuffix(host) {
  const index = wardenOnePslIndex();
  if (!index.loaded) return '';
  const labels = String(host || '').split('.');
  for (let i = 0; i < labels.length; i++) {
    if (index.exception.has(labels.slice(i).join('.'))) return labels.slice(i + 1).join('.');
  }
  let best = '';
  for (let i = 0; i < labels.length; i++) {
    const candidate = labels.slice(i).join('.');
    if (candidate.length <= best.length) break;   // shorter than what is already found
    if (index.plain.has(candidate) || (i + 1 < labels.length && index.wildcard.has(labels.slice(i + 1).join('.')))) best = candidate;
  }
  return best;
}

/* registrableDomain with the complete private list, for trust decisions: "are these two hosts one
 * owner". The answer is never broader than registrableDomain's -- a private rule can only push the
 * boundary further right, and the longer of the two is taken regardless -- so switching a check to
 * this can withdraw trust between two tenants and can never grant it. Lookups keyed by the
 * registered domain (WHOIS, breach records, list membership) keep registrableDomain: alice.webflow.io
 * is a site, but webflow.io is the domain somebody registered. */
function siteIdentity(host) {
  const h = regDomain(host);
  const loose = registrableDomain(h);
  if (!h || loose === h) return loose;
  const suffix = wardenOnePslSuffix(h);
  if (!suffix) return loose;
  if (suffix === h) return h;   // the host is itself a platform suffix: its own identity, as github.io is
  const strict = h.split('.').slice(-(suffix.split('.').length + 1)).join('.');
  return strict.length > loose.length ? strict : loose;
}

function sameSiteIdentity(a, b) {
  const left = siteIdentity(a);
  const right = siteIdentity(b);
  return !!(left && right && left === right);
}

/* Directional host-list matching. Ordinary entries cover their subdomains, as
 * users expect. A private platform apex (github.io) covers only itself rather
 * than every tenant, and opaque infrastructure entries are exact-host only. */
function hostMatchesSite(host, candidate) {
  const h = regDomain(host);
  const d = regDomain(candidate);
  if (!h || !d) return false;
  const opaque = wardenOneSuffixMatch(h, WARDENONE_OPAQUE_TENANT_SUFFIXES)
    || wardenOneSuffixMatch(d, WARDENONE_OPAQUE_TENANT_SUFFIXES);
  if (opaque) return h === d;
  const privateSuffix = wardenOneSuffixMatch(h, WARDENONE_PRIVATE_SUFFIXES)
    || wardenOneSuffixMatch(d, WARDENONE_PRIVATE_SUFFIXES);
  if (privateSuffix && d === privateSuffix) return h === d;
  return h === d || h.endsWith('.' + d);
}
